version: "3"

services:
  api:
    container_name: "api"
    build:
      context: ./api
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    volumes:
      - "./api:/app/api"
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py populate_db &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=c_geolocation_db
      - DB_USER=admin
      - DB_PASS=admin123
    depends_on:
      - db

  db:
    container_name: "db"
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=c_geolocation_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123

  web:
    container_name: "web"
    build:
      context: ./web
      dockerfile: DockerFile
    volumes:
      - "./web:/app/web"
      - "/app/web/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - api
    command: sh -c "npm start"
    stdin_open: true
