export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const FETCH_CUSTOMERS_SUCCESS = "FETCH_CUSTOMERS_SUCCESS";
export const FETCH_CUSTOMERS_FAIL = "FETCH_CUSTOMERS_FAIL";

export const FETCH_CUSTOMER = "FETCH_CUSTOMER";
export const FETCH_CUSTOMER_SUCCESS = "FETCH_CUSTOMER_SUCCESS";
export const FETCH_CUSTOMER_FAIL = "FETCH_CUSTOMER_FAIL";

export const FETCH_CUSTOMER_LOCATION = "FETCH_CUSTOMER_LOCATION";
export const FETCH_CUSTOMER_LOCATION_SUCCESS =
  "FETCH_CUSTOMER_LOCATION_SUCCESS";
export const FETCH_CUSTOMER_LOCATION_FAIL = "FETCH_CUSTOMER_LOCATION_FAIL";
