FROM python:3.8.2-alpine
LABEL maintainer="MF Tech"

ENV PYTHONUNBUFFERED 1

RUN mkdir /app
RUN mkdir /app/api/
WORKDIR /app/api/
COPY . /app/api/
COPY ./requirements.txt /app/api/requirements.txt

RUN apk add --update --no-cache postgresql-client
RUN apk add --update --no-cache --virtual .temp-build-deps \
      gcc libc-dev linux-headers postgresql-dev
RUN pip install -r ./requirements.txt
RUN apk del .temp-build-deps

RUN adduser -D user
USER user

EXPOSE 8000
CMD "python manage.py runserver 0.0.0.0:8000"